version: "3.1"

services:
  scheduler-frontend:
    image: "duo-scheduler-frontend:${BUILD_TAG}"
    ports:
      - 80
    environment:
      - GATEWAY_HOST=gateway:4100
    depends_on:
      - gateway

  cypress:
    build:
      context: "./${USER_OFFICE_SCHEDULER_FRONTEND_DIR}/cypress"
    ipc: host
    entrypoint:
      ["./wait-for-frontend.sh", "scheduler-frontend:80", "npm run cy:run"]
    depends_on:
      - scheduler-frontend
    volumes:
      - "./${USER_OFFICE_SCHEDULER_FRONTEND_DIR}/cypress/screenshots:/tmp/screenshots/"
